- name: test connection to all hosts
  hosts: all
  tasks:
    - name: ping all hosts
      ping:

- name : Installing HAProxy
  hosts: haproxy
  become_method: sudo
  become: true
  roles:
    #- proxy/haproxy
    - proxy/crowdsec

- name: Base Hardening
  hosts: a #all !proxmox
  become_method: sudo
  become: yes
  roles:
      - hardening/rocky

- name: Hardening proxmox
  hosts: a #proxmox
  become_method: sudo
  become: yes
  roles:
      - hardening/proxmox

- name: Install volumes on workers
  hosts: a #k8s_workers
  become_method: sudo
  become: yes
  roles:
      - volumes
  vars:
    partitions: # Ici sur 107 GO
      - { path: "/data", owner: "root", group: "root", mode: "0755", part_start: "0%", part_end: "50%", format: "ext4", disk: "/dev/vdb" } #50Go
      - { path: "/var/lib/containerd", owner: "root", group: "root", mode: "0755", part_start: "50%", part_end: "85%", format: "ext4", disk: "/dev/vdb" } # 37.5Go
      - { path: "/var/lib/kubelet", owner: "root", group: "root", mode: "0755", part_start: "85%", part_end: "95%", format: "ext4", disk: "/dev/vdb" } # 10Go
      - { path: "/run/containerd", owner: "root", group: "root", mode: "0755", part_start: "95%", part_end: "100%", format: "ext4", disk: "/dev/vdb" } # 5.3

- name: Install kubernetes init
  hosts:  a #k8s_masters, k8s_workers
  become_method: sudo
  become: yes
  collections:
    - ansible.posix.firewalld
  serial:
    - 1
    - "100%"
  roles:
    - kubernetes

- name: Install kubernetes app
  hosts: a #kube-master-0
  collections:
      - kubernetes.core #ansible-galaxy collection install kubernetes.core
  roles:
    #- tools/helm
    #- tools/kustomize
    #- kube-app/nginx
    #- kube-app/monitoring
    - kube-app/wazuh
    #- kube-app/database

- name: Install Agents
  hosts: a #all, !proxmox
  become_method: sudo
  become: yes
  roles:
    - agents/node-exporter
    - agents/wazuh-agent