- name : Installing HAProxy
  hosts: a #haproxy
  become_method: sudo
  become: true
  roles:
    - haproxy

- name: Install kubernetes master init
  hosts:  k8s_workers #k8s_masters, k8s_workers
  become_method: sudo
  become: yes
  collections:
    - ansible.posix.firewalld
  serial:
    - 1
    - "100%"
  roles:
    - kubernetes
