- name: Add helm chart repo
  become: yes
  become_method: sudo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Check if ingress-nginx namespace exists
  become: yes
  become_method: sudo
  kubernetes.core.k8s_info:
    kind: namespace
    name: ingress-nginx
  register: __nginx_ingress_namespace

- name: check if monitoring namespace exists
  become: yes
  become_method: sudo
  kubernetes.core.k8s_info:
    kind: namespace
    name: monitoring
  register: __monitoring_namespace

- name: Template values for helm chart
  template:
    src: ingress-nginx.yaml.j2
    dest: /tmp/ingress-nginx.yaml

- name: Deploy ingress-nginx
  become: yes
  become_method: sudo
  shell: "helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --values /tmp/monitoring-values.yaml"
