---
# vars
#monitoring_service_port: 9100
#monitoring_service_path: "/metrics"
#monitoring_service_jobName: "node_exporter"
#monitoring_service_targetLabels: "targetLabel=node_exporter"
#monitoring_service_sourceAgent: "{{ inventory_hostname }}"
#monitoring_service_sourceAgentIP: "{{ ansible_eth0.ipv4.address }}"

- name: Check if node-exporter is ready
  uri:
    url: "http://{{ monitoring_service_sourceAgentIP }}:{{ monitoring_service_port }}{{ monitoring_service_path }}"
    method: GET
    status_code: 200
  register: __node_exporter_ready
  until: __node_exporter_ready.status == 200
  retries: 5
  delay: 10

- name: Check if monitoring namespace exist
  become: yes
  become_method: sudo
  kubernetes.core.k8s_info:
    kind: Namespace
    name: monitoring
  register: __monitoring_namespace
  changed_when: False
  ignore_errors: yes
  failed_when: __monitoring_namespace.resources | length == 0

- name: Create Probe
  become: yes
  become_method: sudo
  kubernetes.core.k8s:
    definition:
      kind: Probe
      apiVersion: monitoring.coreos.com/v1
      metadata:
        name: "{{ monitoring_service_sourceAgent }}"
        namespace: monitoring
      spec:
        jobName: "{{ monitoring_service_jobName }}"
        interval: 10s
        scrapeTimeout: 10s
        prober:
          url: "{{ monitoring_service_sourceAgentIP }}:{{ monitoring_service_port }}"
          path: "{{ monitoring_service_path }}"
          scheme: "http"
          targets:
            staticConfig:
              static:
                - "{{ monitoring_service_sourceAgentIP }}:{{ monitoring_service_port }}"



