- name: Install base sec tools
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - iptables-services
    - firewalld

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: modify sshd config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?ListenAddress ::"
      line: "ListenAddress {{ ansible_eth0.ipv4.address }}"
  notify: restart sshd


- name: set sudo password for user
  user:
    name: "{{ ansible_user }}"
    password: "{{ ansible_sudo_pass | password_hash('sha512') }}"

- name: set sudoers
  lineinfile:
    regexp: "^{{ ansible_user }} ALL"
    line: "{{ ansible_user }} ALL=(ALL) ALL"
    path: /etc/sudoers



