- name: Open SELinux(syslog udp socket) port on proxy
  become: yes
  become_method: sudo
  shell: "semanage port -a -t syslogd_port_t -p udp 512"

- name: Configure ryslog for haproxy
  become: true
  template:
    src: rsyslog_haproxy.conf.j2
    dest: /etc/rsyslog.d/49-haproxy.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_rsyslog


- meta: flush_handlers