- name: Install haproxy bouncer from github
  get_url:
    url: https://github.com/crowdsecurity/cs-haproxy-bouncer/releases/download/v0.0.7/crowdsec-haproxy-bouncer.tgz
    dest: /tmp/crowdsec-haproxy-bouncer.tgz

- name: Extract haproxy bouncer
  unarchive:
    src: /tmp/crowdsec-haproxy-bouncer.tgz
    dest: /tmp
    remote_src: yes

- name: Install haproxy bouncer
  shell: "cd /tmp/crowdsec-haproxy-bouncer-v* && ./install.sh"

- name: Install crowdsec haproxy parser
  shell: "cscli parsers install crowdsecurity/haproxy-logs"

- name: Check if bot is already registered
  shell: "cscli bouncers list | grep crowdsec-haproxy-bouncer"
  register: bouncer_output
  ignore_errors: yes

- name: Configure and register haproxy bouncer
  when: bouncer_output.rc != 0
  block:
    - name: Register haproxy bouncer
      when: bouncer_output.rc != 0
      shell: "cscli bouncers add crowdsec-haproxy-bouncer"
      register: __bouncer_output

    - name: Create crowdsec directory
      file:
        path: /etc/crowdsec/bouncers
        state: directory
        mode: 0755

    - name: Configure crowdsec
      template:
        src: crowdsec-haproxy-bouncer.conf.j2
        dest: /etc/crowdsec/bouncers/crowdsec-haproxy-bouncer.conf
        owner: root
        group: root
        mode: 0644