- name: Install crowdsec
  when: false
  include_tasks: install_crowdsec.yml

- name: Install haproxy bouncer
  when: false
  include_tasks: install_bouncer.yml

- name: Install rsyslog
  when: false
  include_tasks: configure_rsyslog.yml

- name: Configure haproxy
  include_tasks: configure_haproxy.yml

- name: Install crowdsec Haproxy collection
  become: true
  shell: "cscli collections install crowdsecurity/haproxy"
  notify: restart_crowdsec






