---
# tasks file for roles/kubernetes

- name: Pre-requisites
  include_tasks: pre-requisites.yml

- name: Init cluster
  include_tasks: init.yml
  when: ansible_hostname == kubeadm_init_node and ansible_hostname in groups[kubeadm_master_group_name]

- name: Join cluster
  include_tasks: join.yml
  when: ansible_hostname != kubeadm_init_node

