- name: add key for wazuh
  rpm_key:
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: add wazuh repo
  yum_repository:
    name: wazuh
    description: Wazuh repository
    baseurl: https://packages.wazuh.com/4.x/yum/
    gpgcheck: no
    gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    protect: yes
    enabled: yes
    state: present

- name: install wazuh agent
  yum:
    name: wazuh-agent
    state: present

- name: Check if auth password secret exist
  delegate_to: kube-master-0
  become: yes
  become_method: sudo
  kubernetes.core.k8s_info:
    kind: secret
    namespace: wazuh
    name: wazuh-authd-pass
  register: __wazuh_pass


- name: Configure wazuh
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: 0640

- name: Define password
  when: __wazuh_pass.resources | length == 1
  lineinfile:
    state: present
    create: yes
    insertafter: "EOF"
    regexp: "^"
    mode: 0640
    owner: root
    group: wazuh
    path: "/var/ossec/etc/authd.pass"
    line: "{{ __wazuh_pass.resources[0].data['authd.pass'] | b64decode }}"

- name: Configure wazuh
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: wazuh
    mode: 0640

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: restart wazuh
  service:
    name: wazuh-agent
    state: restarted
    enabled: yes

- name: disable repo
  yum_repository:
    name: wazuh
    baseurl: https://packages.wazuh.com/4.x/yum/
    description: Wazuh repository
    enabled: no
    state: present
