- name: Edit service (add external IP)
  replace:
    path: "/tmp/wazuh-kubernetes/wazuh/{{ item.path }}"
    regexp: "^"
    replace: "externalIPs: ['{{ item.ip }}']"
    state: present
    insertafter: EOF
    create: True


  lineinfile:
    dest=/home/foo/.bashrc
    backup=yes
    line="[[ -s ${pythonbrew.bashrc_path} ]] && source ${pythonbrew.bashrc_path}"
    owner=foo
    regexp='^'
    state=present
    insertafter=EOF
    create=True

#  externalIPs:
#  - 10.0.0.30



