- name: reload_haproxy
  service:
    name: haproxy
    state: reloaded
    enabled: yes

- name: restart_haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: start_haproxy
  service:
    name: haproxy
    state: started
    enabled: yes